name: CI/CD to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/YOUR_APP_NAME:latest .

    - name: Configure gcloud CLI
      uses: google-github-actions/setup-gcloud@master
      with:
        project_id: YOUR_PROJECT_ID
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true

    - name: Push to Google Container Registry
      run: |
        docker tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/YOUR_APP_NAME:latest gcr.io/YOUR_PROJECT_ID/YOUR_APP_NAME:latest
        docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/YOUR_APP_NAME:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy YOUR_APP_NAME \
        --image=gcr.io/${{ secrets.GCP_PROJECT_ID }}/YOUR_APP_NAME:latest \
        --platform=managed \
        --region=us-west1 \
        --allow-unauthenticated
